backend/.gitignore, backend/src/main/resources/application.yml
.yml 파일 중 application.yml 은 git 관리로 추가하였습니다.
=> feat: .gitignore 수정 - application.yml 은 git 관리로 추가

backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/StudyContentDataInit.java
=> fix: csv 파일 경로 수정

backend/build.gradle, backend/src/main/java/com/java/NBE4_5_1_7/domain/member/entity/Member.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/member/repository/MemberRepository.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/member/service/AuthTokenService.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/member/service/MemberService.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/testlogin/TestController.java, backend/src/main/java/com/java/NBE4_5_1_7/global/Rq.java, backend/src/main/java/com/java/NBE4_5_1_7/global/app/AppConfig.java, backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/StudyContentDataInit.java, backend/src/main/java/com/java/NBE4_5_1_7/global/dto/Empty.java, backend/src/main/java/com/java/NBE4_5_1_7/global/dto/RsData.java, backend/src/main/java/com/java/NBE4_5_1_7/global/entity/BaseEntity.java, backend/src/main/java/com/java/NBE4_5_1_7/global/entity/BaseTime.java, backend/src/main/java/com/java/NBE4_5_1_7/global/exception/GlobalExceptionHandler.java, backend/src/main/java/com/java/NBE4_5_1_7/global/exception/ServiceException.java, backend/src/main/java/com/java/NBE4_5_1_7/global/security/CustomAuthenticationSuccessHandler.java, backend/src/main/java/com/java/NBE4_5_1_7/global/security/CustomAuthorizationRequestResolver.java, backend/src/main/java/com/java/NBE4_5_1_7/global/security/CustomOauth2UserService.java, backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java, backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityUser.java, backend/src/main/java/com/java/NBE4_5_1_7/standard/Ut.java, backend/src/main/resources/application.yml, backend/src/test/java/com/java/NBE4_5_1_7/domain/member/service/AuthTokenServiceTest.java
OAuth2를 사용한 카카오 로그인 구현
JWT 생성 test 추가
member entity 관리를 위한 repository, service 추가
application-secret.yml 하위 보안 사항 추가 슬랙 확인 부탁드립니다.
=> feat: OAuth2 카카오 로그인, JWT

frontend/src/app/components/Header.tsx
=> feat: 관리자 header UI 구현

backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java
SecurityConfig 미반영 된 내용 급하게 pr 보내고 바로 merge 하도록 하겠습니다.
이전의 내용에서 수정은 SecurityConfig 에서만 이루어졌습니다.
=> feat: security config cors 허용, 인증 부분 주석 처리

backend/src/main/java/com/java/NBE4_5_1_7/domain/study/controller/StudyMemoController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/entity/StudyMemo.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/repository/StudyMemoRepository.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/service/StudyMemoService.java
메모 작성 기능 구현
1. 메모 작성 기능 구현
2. 메모 관련 디렉토리 생
=> feat: 메모 작성 기능 구현

backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/controller/InterviewCommentController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/dto/InterviewCommentDetailDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/entity/InterviewContentComment.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/repository/InterviewCommentRepository.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/service/InterviewCommentService.java
기술 면접 답변 CRUD API 구현
feat: 기술 면접 답변 CRUD API 구현: 생성, 조회, 수정, 삭제 API 구현했습니다.
=> feat: 기술 면접 답변 CRUD API 구현

backend/src/main/java/com/java/NBE4_5_1_7/domain/study/controller/StudyContentController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/controller/StudyMemoController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/dto/request/StudyContentUpdateRequestDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/service/StudyContentService.java, backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/StudyContentDataInit.java, backend/src/main/resources/application.yml
학습 컨텐츠 관리 기능 구현 및 리펙토링
1. 학습 컨텐츠 수정 기능 구현
2. 학습 컨텐츠 삭제 기능 구현
3. 학습 컨텐츠에 관한 메서드 명 수정
4. 학습 컨텐츠 첫 번째 카테고리 DB 누락 사항 수정
5. 카테고리 Map 방식으로 반환하는 기능 추가
=> feat: 학습 컨텐츠 관리 기능 구현

backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/controller/InterviewCommentController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/dto/request/InterviewCommentRequestDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/dto/response/InterviewCommentResponseDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/service/InterviewCommentService.java
authorization 추가 및 dto 요청/응답 분리
authorization 추가 및 dto 요청/응답 분리
DTO에서 memberId 필드를 삭제하고, 이를 authorization으로 대체했습니다.
=> fix: authorization 추가 및 dto 요청/응답 분리

frontend/src/app/admin/content/page.tsx, frontend/src/app/admin/page.tsx, frontend/src/app/admin/questions/page.tsx, frontend/src/app/styles/admin.module.css
- 대시보드 기초 UI 생성
- 학습 컨텐츠, 질문 관리 페이지 삭제 버튼 추가 및 CSS 수정
=> feat: 관리자 페이지 대시보드 UI

frontend/src/app/ClientLayout.tsx, frontend/src/app/ClientPage.tsx, frontend/src/app/components/Header.tsx, frontend/src/app/login/page.tsx
=> feat: 메인 페이지 및 컴포넌트 비율 수정

backend/src/main/java/com/java/NBE4_5_1_7/domain/study/repository/StudyContentRepository.java, backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/StudyContentDataInit.java, backend/src/main/resources/application.yml, frontend/src/app/studyContent/studyContentBody.tsx
학습 컨텐츠 마크다운 적용, 메모 저장 자격 검증 완료
1. 학습 컨텐츠 내용 마크다운 적용
2. 메모 저장 시 자격 검증 안되던 문제 해결
3. 학습 컨텐츠 서버 재실행 시 마다 중복되어 DB에 저장되는 현상 해결
=> Refactor/#75 학습 컨텐츠 마크다운, 메모 저장 자격 검증 완료

backend/src/main/java/com/java/NBE4_5_1_7/domain/study/controller/StudyContentAdminController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/dto/StudyContentDetailDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/entity/FirstCategory.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/repository/StudyContentRepository.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/service/StudyContentAdminService.java, frontend/src/app/admin/content/page.tsx
관리자용 컨트롤러와 서비스를 따로 구현했습니다. 추후에 같은 기능을 하는 api는 하나로 통일하고자 합니다.
=> feat: 관리자 학습 컨텐츠 관리 페이지 api 연결

backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/controller/InterviewBookmarkController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/service/InterviewService.java, frontend/package.json, frontend/src/app/mypage/ClientPage.tsx, frontend/src/app/styles/mypage.module.css, frontend/src/lib/backend/apiV1/schema.d.ts
내 노트 조회/삭제 API 연동 및 CSS
내 노트 조회/삭제 API 연동 및 CSS
=> feat: 내 노트 조회/삭제 API 연동 및 CSS

backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/InterviewContentDataInit.java, backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/StudyContentDataInit.java, backend/src/main/resources/application.yml, frontend/src/app/interview/category/page.tsx, frontend/src/app/interview/keyword/page.tsx, frontend/src/app/interview/random/page.tsx, frontend/src/lib/backend/apiV1/schema.d.ts
=> fix: interview page 원상복구

backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/dto/request/InterviewCommentRequestDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/repository/InterviewCommentRepository.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/service/InterviewCommentService.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/entity/FirstCategory.java, frontend/src/app/components/Header.tsx, frontend/src/app/mypage/ClientPage.tsx, frontend/src/lib/backend/apiV1/schema.d.ts
#79 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요
로그인 후 마이페이지 링크 표시 및 코드 리팩토링 작업 진행
=> [Refactor] 로그인 후 마이페이지 링크 표시 및 코드 리팩토링 작업 진행

backend/build.gradle, backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/controller/InterviewController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/controller/InterviewLikeController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/entity/InterviewContentLike.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/entity/dto/response/InterviewResponseDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/repository/InterviewContentLikeRepository.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/service/InterviewLikeService.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/service/InterviewService.java, backend/src/main/java/com/java/NBE4_5_1_7/global/config/RedissonConfig.java, backend/src/main/resources/application.yml, frontend/src/app/interview/all/page.tsx, frontend/src/app/interview/category/page.tsx, frontend/src/app/interview/keyword/page.tsx, frontend/src/app/interview/random/page.tsx, frontend/src/lib/backend/apiV1/schema.d.ts
> #87
> 면접 컨텐츠 좋아요 기능 구현
> 해당 사용자가 이미 좋아요를 눌렀다면 -> 좋아요 취소 버튼으로 보이도록 설정 , 해당 버튼을 누르면 좋아요 취소가 됩니다.
=> Feat/#87 면접 컨텐츠 - 좋아요 기능 구현

backend/src/main/java/com/java/NBE4_5_1_7/domain/study/controller/StudyMemoController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/dto/response/StudyMemoResponseDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/repository/StudyMemoRepository.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/service/StudyContentService.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/service/StudyMemoService.java, frontend/src/app/studyContent/studyContentBody.tsx, frontend/src/app/studyContent/studyContentCategory.tsx, frontend/src/app/styles/studyContent.module.css
학습 컨텐츠에 대한 메모가 존재하는 경우 작성했을 때 수정하는 로직 구현
1. 학습 메모가 이미 있는 경우 나의 메모 작성 시 기존 메모의 내용을 수정하게 끔 수정
2. 기존 메모가 있는 지 확인하는 메모 단건 조회 추가
3. 코드 리펙토링
4. 비로그인 상태에서 메모 작성, 메모 조회 시 알림과 함께 로그인 화면으로 리다이렉트
_No response_
=> Feat/#84 기존 메모가 있는 지 확인하는 메모 단건 조회 추가

backend/src/main/java/com/java/NBE4_5_1_7/global/config/OpenApiConfig.java, backend/src/main/resources/application.yml, frontend/src/lib/backend/apiV1/schema.d.ts
- swagger 에 cookie 적용
- 적용 방법은 slack 통해서 공유 드리겠습니다
=> swagger access token 적용

backend/build.gradle, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatMessageController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatRoomController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/dto/request/ChatRoomRequestDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/dto/response/ChatMessageResponseDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/dto/response/ChatRoomResponseDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/entity/ChatMessage.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/entity/ChatRoom.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/repository/ChatMessageRepository.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/repository/ChatRoomRepository.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatPublisher.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatRoomService.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatSubscriber.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/controller/InterviewCommentController.java, backend/src/main/java/com/java/NBE4_5_1_7/global/config/WebSocketConfig.java, backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/StudyContentDataInit.java, backend/src/main/java/com/java/NBE4_5_1_7/global/util/LockManager.java, frontend/src/lib/backend/apiV1/schema.d.ts
#103 
WebSocket + STOMP + Redis을 활용하여 채팅 기능 API 구현했습니다.
1. WebSocket: HTTP보다 빠른 양방향 통신, 실시간 처리 최적화
2. STOMP: 메시징 프로토콜, 메시지 전달을 위한 pub/sub 지원.
3. Redis: 멀티 서버에서의 메시지 동기화, 부하 분산, 확장성.
=> [Feat] 관리자와의 채팅 기능 구현

backend/src/main/java/com/java/NBE4_5_1_7/domain/study/controller/StudyMemoController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/controller/StudyMemoLikeController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/dto/request/StudyMemoCreateRequestDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/dto/response/StudyMemoResponseDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/entity/StudyMemo.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/entity/StudyMemoLike.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/repository/StudyMemoLikeRepository.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/repository/StudyMemoRepository.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/service/StudyMemoLikeService.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/study/service/StudyMemoService.java, frontend/src/app/studyContent/memoList/[selectedContentId]/page.tsx, frontend/src/app/studyContent/studyContentBody.tsx, frontend/src/app/styles/studyContent.module.css
#93 
학습 메모 공유 여부 추가
학습 메모 좋아요 기능 추가
학습 컨텐츠에 대한 다른 사용자들이 작성한 공개 메모 리스트 구현
=> Feat/#93 학습 컨텐츠 메모 공유 기능 구현

frontend/package.json, frontend/src/app/ClientPage.tsx, frontend/src/app/components/Header.tsx
>  #120
> 메인 페이지 및 헤더 컴포넌트 UI 개선
=> 메인 페이지 및 Header 수정

backend/Dockerfile, backend/src/main/java/com/java/NBE4_5_1_7/global/config/RedisConfig.java, backend/src/main/java/com/java/NBE4_5_1_7/global/init/DevInitData.java
#105 
**자바 버전 변경 java openJDK 23 -> java amazoncorrettoJDK 21**
**Project Structure창 (단축키 : SHIFT+CTRL+ALT+S)**
SDK 변경                                 
Language Level 변경    
**Project Setting (단축키 : CTRL+ALT+S)**
Build,Execution,Deployment  -> Build Tools -> Gradle 
Gradle JVM 변경   
**Build,Execution,Deployment  -> Compiler -> Java Compiler**
Project bytecode version 변경
=> refactor&fix:java 23->21 ver change, Dockerfile change

frontend/src/app/admin/interview/header.tsx, frontend/src/app/admin/interview/modal/interviewCreateModal.tsx, frontend/src/app/admin/interview/modal/interviewDetailModal.tsx, frontend/src/app/admin/interview/page.tsx, frontend/src/app/admin/studyContent/content.tsx, frontend/src/app/admin/studyContent/header.tsx, frontend/src/app/admin/studyContent/modal/contentCreateModal.tsx, frontend/src/app/admin/studyContent/modal/contentEditModal.tsx, frontend/src/app/admin/studyContent/page.tsx, frontend/src/app/styles/admin/content.module.css, frontend/src/app/styles/admin/header.module.css, frontend/src/app/styles/admin/modal/contentDetailModal.module.css, frontend/src/app/styles/admin/page.module.css, frontend/src/app/styles/admin/sidebar.module.css
> #115 
> 관리자 페이지에서 CRUD 기능을 한 후 페이지 새로고침이 일어나지 않아 화면에 바로 적용되지 않는 문제가 있습니다.
=> feat: 데이터 등록 모달 페이지 구현

backend/src/main/java/com/java/NBE4_5_1_7/Nbe4517Application.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/GuestRoomController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/model/ChatRoom.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/model/Message.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/repository/ChatRoomRepository.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatService.java, backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java, backend/src/main/resources/application.yml, frontend/package.json, frontend/src/app/admin/chat/page.tsx, frontend/src/app/chat/FlotingChat.tsx, frontend/src/app/components/Header.tsx, frontend/src/app/login/loginMemberStore.tsx
> #147 
플로팅 채팅과 관리자 채팅 관리 페이지입니다.
관리자 페이지 대시보드 페이지를 제거했습니다.
UI는 이후 더 개선할 계획입니다.
=> feat: 고객 문의 관리 UI

backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatController.java, frontend/src/app/chat/FlotingChat.tsx, frontend/src/lib/backend/apiV1/schema.d.ts
=> [Fix] 유실된 코드 일부 복원 및 시스템 메세지 추가

backend/src/main/java/com/java/NBE4_5_1_7/domain/news/controller/NewsController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/news/dto/responseDto/JobResponseDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/news/dto/responseDto/JobsDetailDto.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/news/service/NewsService.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/payment/service/PaymentService.java
> ex) #이슈번호, #이슈번호
#151 
채용공고 단건조회 API 구현
=> Feat/#151 채용공고 단건조회 API 구현

backend/src/main/java/com/java/NBE4_5_1_7/domain/mail/EmailService.java, backend/src/main/resources/templates/email-template.html, frontend/src/app/admin/chat/page.tsx
=> fix: 메시지의 시간을 한국 기준으로 변경

backend/src/main/java/com/java/NBE4_5_1_7/domain/news/controller/NewsController.java, backend/src/main/java/com/java/NBE4_5_1_7/domain/news/service/NewsService.java, frontend/src/app/news/[recrutPblntSn]/page.tsx, frontend/src/app/news/jobs.tsx, frontend/src/app/news/news.tsx, frontend/src/app/news/page.tsx
> ex) #이슈번호, #이슈번호
#157 
1. 채용 공고 목록 페이지 구현
2. 채용 공고 세부사항 페이지 구현
=> Feat/#157 채용 공고 API - 프론트엔드

frontend/src/app/chat/FlotingChat.tsx, frontend/src/lib/backend/apiV1/schema.d.ts
=> [Fix] 채팅 컴포넌트를 제일 상위로

frontend/src/app/studyContent/studyContentBody.tsx
> ex) #이슈번호, #이슈번호
#164 
스크롤바 활성화
=> style: 학습컨텐츠 css 높이 제한

frontend/src/app/admin/interview/header.tsx, frontend/src/app/admin/interview/modal/interviewCreateModal.tsx, frontend/src/app/admin/interview/page.tsx, frontend/src/app/admin/interview/sidebar.tsx, frontend/src/app/admin/studyContent/sidebar.tsx
> #166 
관리자 페이지의 학습 콘텐츠와 면접 질문 관리에 사이드바 UI 수정
=> refactor: 사이드 바 UI 수정 (관리자 페이지)

frontend/src/app/admin/chat/page.tsx, frontend/src/app/admin/interview/header.tsx, frontend/src/app/admin/interview/modal/interviewCreateModal.tsx, frontend/src/app/admin/interview/page.tsx, frontend/src/app/admin/interview/sidebar.tsx, frontend/src/app/admin/studyContent/sidebar.tsx
=> fix: 메시지 시간 문제 해결

frontend/src/app/admin/interview/content.tsx, frontend/src/app/admin/interview/header.tsx, frontend/src/app/admin/interview/modal/interviewCreateModal.tsx, frontend/src/app/admin/interview/modal/interviewDeleteModal.tsx, frontend/src/app/admin/interview/modal/interviewDetailModal.tsx, frontend/src/app/admin/interview/modal/interviewEditModal.tsx, frontend/src/app/admin/studyContent/content.tsx, frontend/src/app/admin/studyContent/header.tsx, frontend/src/app/admin/studyContent/modal/contentCreateModal.tsx, frontend/src/app/admin/studyContent/modal/contentDeleteModal.tsx, frontend/src/app/admin/studyContent/modal/contentDetailModal.tsx, frontend/src/app/admin/studyContent/modal/contentEditModal.tsx, frontend/src/app/admin/studyContent/page.tsx, frontend/src/app/admin/studyContent/sidebar.tsx, frontend/src/app/styles/admin/content.module.css
=> refactor: 모달 UI 수정 (관리자 페이지)
